- name: Create hooks directory
  ansible.builtin.file:
    path: /etc/pacman.d/hooks
    state: directory
    mode: "0755"

- name: Enable pacman multilib repo
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertbefore: "# An example of a custom package repository.  See the pacman manpage for"
  with_items:
    - regexp: "^\\[multilib\\]|#\\[multilib\\]$"
      line: "[multilib]"
    - regexp: "^Include|#Include = /etc/pacman.d/mirrorlist$"
      line: "Include = /etc/pacman.d/mirrorlist"

- name: Install packages
  community.general.pacman:
    name:
      - sddm
      - plasma-meta
      - kde-applications-meta
      - libappindicator-gtk3
      - python-gpgme
      - networkmanager
      - wayland
      # - packagekit-qt6 # Support for pacman in discover is not good so dont install packagekit-qt6 yet
      - gnupg
      - code
      - xdg-desktop-portal
      - xdg-desktop-portal-kde
      - flatpak
      - hyfetch
      - macchina
      - libpcap
      - bash-completion
      - croc
      - wireguard-tools
      - qbittorrent
      - discord
      - element-desktop
      - bluez-utils
      - fprintd
      - tuned-ppd
      - steam
      - winetricks

- name: Install AUR packages
  kewlfft.aur.aur:
    name:
      - evdi-dkms
      - displaylink
      - yay
      - librewolf-bin
      - ventoy-bin
      - vagrant
      - infisical-bin
      - dell-command-configure
      - kuro
      # - onedrivegui # Can be installed when the maintainer fix the dependency versions
      - onedrive-abraunegg
      - dropbox
      - autotrace-git
      - anydesk-bin
      - htpasswd
      # - proton-mail # Build fails
      # - joplin-desktop # Build tage too many system resources
      - onlyoffice-bin
      - gitkraken
      - proton-pass-bin
      - protonup-qt
      - protontricks
  become: true
  become_user: "{{ host.user.wheel.name }}"

- name: Install flatpak apps
  community.general.flatpak:
    name:
      - me.proton.Mail
      # - com.axosoft.GitKraken
      - net.cozic.joplin_desktop
      # - org.onlyoffice.desktopeditors
    state: present

- name: Install nodejs packages
  community.general.npm:
    global: true
    name: dclint
    state: latest

- name: Create directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  with_items:
    - path: /etc/sddm.conf.d/
      mode: u+w,ugo+rx
      owner: root
      group: root
    - path: "/home/{{ host.user.wheel.name }}/.local/bin"
      mode: u+w
      owner: "{{ host.user.wheel.name }}"
      group: wheel

- name: Download albiondata-client
  ansible.builtin.get_url:
    dest: ~/Hentet/update-linux-amd64.gz
    url: https://github.com/ao-data/albiondata-client/releases/latest/download/update-linux-amd64.gz
    mode: u+r
  become: true
  become_user: "{{ host.user.wheel.name }}"

- name: Unpack albiondata-client
  ansible.builtin.shell:
    cmd: gzip -dc < ~/Hentet/update-linux-amd64.gz > ~/.local/bin/albiondata-client
    creates: ~/.local/bin/albiondata-client
  become: true
  become_user: "{{ host.user.wheel.name }}"

- name: Set albiondata-client execution permission
  ansible.builtin.file:
    mode: u+x
    path: ~/.local/bin/albiondata-client
  become: true
  become_user: "{{ host.user.wheel.name }}"

- name: Allow albiondata-client to capture data
  community.general.capabilities:
    capability: "{{ item }}"
    path: ~/.local/bin/albiondata-client
    state: present
  with_items:
    - cap_net_raw=eip
    - cap_net_admin=eip

- name: Copy files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: u+w,ugo+rx
  with_items:
    - src: etc/sddm.conf.d/wayland.conf
      dest: /etc/sddm.conf.d/
    - src: lumo.png
      dest: /usr/share/pixmaps/lumo-pwa.png
    - src: lumo.desktop
      dest: /usr/share/applications/lumo-pwa.desktop
    - src: lumo.service
      dest: "/home/{{ host.user.wheel.name }}/.config/systemd/user"

- name: Enable services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
  with_items:
    - sddm.service
    - firewalld.service
    - NetworkManager.service
    - pacman-filesdb-refresh.timer
    - docker.service
    - bluetooth.service

- name: Enable user services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
    scope: user
  with_items:
    - dropbox.service
  become: true
  become_user: "{{ host.user.wheel.name }}"

- name: Add user to video group
  ansible.builtin.user:
    name: "{{ host.user.wheel.name }}"
    groups: video
    append: true
